routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('categories', 'HomeController@categories')->name('home.categories');
Route::get('products/{query?}', 'HomeController@products')->name('home.products');
Route::get('products/category/{category}/{query?}', 'HomeController@categoryProducts')->name('home.category.products');
Route::get('products/detail/{product}', 'HomeController@showProduct')->name('home.products.show');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/profile', 'UserController@show')->name('profile');
    Route::get('/profile/edit', 'UserController@edit')->name('profile.edit');
    Route::put('/profile/update', 'UserController@update')->name('profile.update');
});

//Resources
Route::group(['prefix' => 'backend', 'middleware' => 'role:admin'], function () {
    Route::get('/', 'Backend\HomeController@index')->name('backend');
    Route::resource('categories', 'Backend\CategoryController');
    Route::resource('products', 'Backend\ProductController');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        
                    </ul>
                    <div class="search-bar">
                        @if (Route::currentRouteName() == 'home.category.products')
                            <form class="navbar-form navbar-left" role="search" method="GET">
                        @else
                            <form class="navbar-form navbar-left" role="search" method="GET" action="{{ route('home.products') }}">
                        @endif
                            <input name="query" type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                            @csrf
                        </form>
                    </div>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a href="{{ route('profile') }}" class="dropdown-item" >Profil</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="sidenav shadow-sm bg-white">
                @if (auth()->user() && auth()->user()->hasRole('admin'))
                    <a href="{{ route('backend') }}">Backend</a>
                @endif
                <a href="{{ route('home.categories') }}">Catégories</a>
                <a href="{{ route('home.products') }}">Produits</a>
            </div>
            <div class="main">
                <div class="container">
                    <div class="mobile-search-bar">
                        @if (Route::currentRouteName() == 'home.category.products')
                            <form class="navbar-form navbar-left" role="search" method="GET">
                        @else
                            <form class="navbar-form navbar-left" role="search" method="GET" action="{{ route('home.products') }}">
                        @endif
                            <input name="query" type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                            @csrf
                        </form>
                    </div>
                </div>
                @yield('content')
            </div>
        </main>
</body>
</html>

resources/views/layouts/backend.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        
        <nav class="navbar navbar-expand-md navbar-light bg-grey shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        
                    </ul>
                    <div class="search-bar">
                        @if (Route::currentRouteName() == 'categories.index')
                            <form class="navbar-form navbar-left" role="search" method="GET">
                        @else
                            <form class="navbar-form navbar-left" role="search" method="GET" action="{{ route('products.index') }}">
                        @endif
                            <input name="query" type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                            @csrf
                        </form>
                    </div>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a href="{{ route('profile') }}" class="dropdown-item" >Profil</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="sidenav shadow-sm bg-grey">
                <a href="{{ route('backend') }}">Backend</a>
                <a href="{{ route('categories.index') }}">Catégories</a>
                <a href="{{ route('products.index') }}">Produits</a>
            </div>
            <div class="main">
                <div class="container">
                    <div class="mobile-search-bar">
                        @if (Route::currentRouteName() == 'home.category.products')
                            <form class="navbar-form navbar-left" role="search" method="GET">
                        @else
                            <form class="navbar-form navbar-left" role="search" method="GET" action="{{ route('home.products') }}">
                        @endif
                            <input name="query" type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                            @csrf
                        </form>
                    </div>
                </div>
                @yield('content')
            </div>
        </main>
</body>
</html>